export const getInvoiceData = (data = {}) => ({
  logo: data.logo || null,
  companyName: data.companyName || '',
  companyAddress: data.companyAddress || '',
  billToName: data.billTo?.name || '',
  billToAddress: data.billTo?.address || '',
  shipToName: data.shipTo?.name || '',
  shipToAddress: data.shipTo?.address || '',
  invoiceNumber: data.invoiceNumber || '',
  invoiceDate: data.invoiceDate || '',
  poNumber: data.poNumber || '',
  dueDate: data.dueDate || '',
  items: data.items || [],
  terms: data.terms || [],
  subtotal: data.subtotal || 0,
  taxAmount: data.taxAmount || 0,
  total: data.total || 0,
  bankName: data.paymentInfo?.bankName || data.payment?.bankName || '',
  accountNo: data.paymentInfo?.accountNo || data.payment?.accountNumber || '',
  ifscCode: data.paymentInfo?.ifscCode || data.payment?.ifscCode || '',
  upiId: data.paymentInfo?.upiId || data.payment?.upiId || '',
  signature: data.signature || null,
  qrCode: data.qrCode || null,
  email: data.buisness?.email || '',
  phone: data.buisness?.phone || '',
  website: data.website || '',
});
