export const getInvoiceData = (data = {}) => ({
  logo: data.logo || null,
  companyName: data.companyName || 'Creative Designs',
  companyAddress: data.companyAddress || 'Tech street, n°3, 1234\nYour Town.',
  billToName: data.billTo?.name || 'Infrabuild Pvt Ltd',
  billToAddress: data.billTo?.address || 'Andheri East\nMumbai-40069',
  shipToName: data.shipTo?.name || 'InfraBuild Pvt Ltd',
  shipToAddress: data.shipTo?.address || '12 Bailey Road,\nPatna - 800014',
  invoiceNumber: data.invoiceNumber || 'BFA-220',
  invoiceDate: data.invoiceDate || '01/01/2025',
  poNumber: data.poNumber || 'PO-2025-7788',
  dueDate: data.dueDate || '21/01/2025',
  items: data.items || [
    { qty: 1, description: 'Website Design Services', unitPrice: 8500.00, amount: 8500.00 },
    { qty: 2, description: 'Premium Template Pack', unitPrice: 950.00, amount: 1900.00 },
    { qty: 3, description: 'Annual Maintenance', unitPrice: 1200.00, amount: 3600.00 },
  ],
  terms: data.terms || [
    'Payment is due within 15 days',
    'Late fee: 2% after due date',
    'Bank Transfer accepted'
  ],
  subtotal: data.subtotal || 14000.00,
  taxAmount: data.taxAmount || 1680,
  total: data.total || 15680,
  bankName: data.paymentInfo?.bankName || 'State Bank of India',
  accountNo: data.paymentInfo?.accountNo || '123456789032',
  ifscCode: data.paymentInfo?.ifscCode || 'SBIN005678',
  signature: data.signature || null,
  qrCode: data.qrCode || null,
  email: data.email || 'creative@gmail.com',
  phone: data.phone || '+91-7896541236',
  website: data.website || 'creativedesign.com',
});
